version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "4096:4096"
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001 